server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  application:
    name: request-vacation
  datasource:
    url: jdbc:h2:mem:request-vacation
    driver-class-name: org.h2.Driver
    username: admin
    password: admin1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

auth:
  token:
    expired-minute:
      access-token: 60
      refresh-token: 120

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.orm.jpa: DEBUG
    org.springframework.web.client.RestTemplate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
